// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dial1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_dial1, &ui_img_226560045);
    lv_obj_set_width(ui_dial1, LV_SIZE_CONTENT);   /// 500
    lv_obj_set_height(ui_dial1, LV_SIZE_CONTENT);    /// 500
    lv_obj_set_x(ui_dial1, 1);
    lv_obj_set_y(ui_dial1, 1);
    lv_obj_set_align(ui_dial1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_dial1, LV_STATE_USER_4);       /// States
    lv_obj_clear_flag(ui_dial1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_dial1, 200);

    ui_gauge1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_gauge1, &ui_img_1004565353);
    lv_obj_set_width(ui_gauge1, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_gauge1, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_x(ui_gauge1, 2);
    lv_obj_set_y(ui_gauge1, -4);
    lv_obj_set_align(ui_gauge1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gauge1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gauge1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_gauge1, 3);
    lv_img_set_zoom(ui_gauge1, 200);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 1);
    lv_obj_set_y(ui_Label3, 90);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "HELIOS ");

}
