// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT dial

lv_obj_t * ui_dial_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_dial;
    cui_dial = lv_img_create(comp_parent);
    lv_img_set_src(cui_dial, &ui_img_226560045);
    lv_obj_set_width(cui_dial, LV_SIZE_CONTENT);   /// 500
    lv_obj_set_height(cui_dial, LV_SIZE_CONTENT);    /// 500
    lv_obj_set_x(cui_dial, 1);
    lv_obj_set_y(cui_dial, 1);
    lv_obj_set_align(cui_dial, LV_ALIGN_CENTER);
    lv_obj_add_state(cui_dial, LV_STATE_USER_4);       /// States
    lv_obj_clear_flag(cui_dial, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(cui_dial, 200);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DIAL_NUM);
    children[UI_COMP_DIAL_DIAL] = cui_dial;
    lv_obj_add_event_cb(cui_dial, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_dial, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_dial_create_hook(cui_dial);
    return cui_dial;
}

