// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT gauge

lv_obj_t * ui_gauge_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_gauge;
    cui_gauge = lv_img_create(comp_parent);
    lv_img_set_src(cui_gauge, &ui_img_1004565353);
    lv_obj_set_width(cui_gauge, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(cui_gauge, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_x(cui_gauge, 2);
    lv_obj_set_y(cui_gauge, -4);
    lv_obj_set_align(cui_gauge, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_gauge, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_gauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(cui_gauge, 3);
    lv_img_set_zoom(cui_gauge, 200);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_GAUGE_NUM);
    children[UI_COMP_GAUGE_GAUGE] = cui_gauge;
    lv_obj_add_event_cb(cui_gauge, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_gauge, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_gauge_create_hook(cui_gauge);
    return cui_gauge;
}

