// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_GAUGE_H
#define _UI_COMP_GAUGE_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT gauge
#define UI_COMP_GAUGE_GAUGE 0
#define _UI_COMP_GAUGE_NUM 1
lv_obj_t * ui_gauge_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
